version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $container_id
# docker-compose images
# docker-compose logs --tail 20 repo_name

services:

  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dati
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  python_app:
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dati
      POSTGRES_USER: postgres
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    networks:
      - app-tier
    command: 
      "python3 main.py && tail -f /dev/null"


networks:
  app-tier:
    driver: bridge
